apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: group-5-prod
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: kbazaar-api
          image: ghcr.io/kbtg-kampus-classnest-se-java/workshopb2-group-5:c9f6b38c1acd0a7153e42a03b577757262075eb3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.password
            - name: ENABLED_FEATURE_PROMOTION_LIST_API
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: enabled.feature.promotion.list.api
            - name: ENABLE_SHIPPING_FEE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: enabled.shipping.fee
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
